version: "3"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
    restart: on-failure:3
    volumes:
      - wordpress_data:/var/www/html/wordpress
      - nextjs_data:/var/www/html/nextjs_static
    networks:
      - my_server

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: on-failure:3
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my_server
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: on-failure:3
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - my_server
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    restart: on-failure:3
    networks:
      - my_server

  ftp:
    container_name: ftp
    image: ftp
    build: ./requirements/bonus/ftp
    depends_on:
      - wordpress
    ports:
      - 21:21
      - 21000-21010:21000-21010
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: on-failure:3
    networks:
      - my_server

  nextjs:
    container_name: nextjs
    image: nextjs
    build: ./requirements/bonus/nextjs
    volumes:
      - nextjs_data:/nextjs_static
    restart: on-failure:3

  adminer:
    container_name: adminer
    image: adminer
    build: ./requirements/bonus/adminer
    depends_on:
      - mariadb
    restart: on-failure:3
    networks:
      - my_server

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      # device: /home/joonhan/data/wordpress
      device: ../data/wordpress
      o: bind

  mariadb_data:
    driver: local # Save in host OS (Available for other volume plugin)
    driver_opts:
      type: none # File system type (like tmpfs, shm, ramfs)
      # device: /home/joonhan/data/mysql
      device: ../data/mysql
      o: bind

  nextjs_data:
    driver: local # Save in host OS (Available for other volume plugin)
    driver_opts:
      type: none # File system type (like tmpfs, shm, ramfs)
      # device: /home/joonhan/data/nextjs
      device: ../data/nextjs
      o: bind

networks:
  my_server:
    driver: bridge
